FROM node:latest


ENV PROTO_HOME="/.proto"
ENV PATH="$PROTO_HOME/shims:$PROTO_HOME/bin:$PATH"
ENV SHELL=/bin/bash



RUN curl -fsSL https://moonrepo.dev/install/proto.sh | bash


ADD .prototools .prototools
RUN proto use